@BASE_URL = http://localhost:5000
@TOKEN = 

# Register Request
POST {{BASE_URL}}/create
Content-Type: application/json

{
    "firstName": "Pareena",
    "lastName":"Thapa",
    "email":"thapapareena@gmail.com",
    "password":"12345678",
    "confirmPassword":"12345678"
}

###

# Login Request
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "email":"thapapareena@gmail.com",
    "password":"12345678"
}

###

# Get User Detail
GET {{BASE_URL}}/me
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###